#!/bin/sh

# ##########################################
# ## filters chromium history through fzf ##
# ##########################################

[ -n "$MXC_V" ] && . "$HOME/.profile"

cols=$(( COLUMNS / 3 ))
sep='{::}'

cp -f "$HOME"/.config/chromium/Default/History /tmp/h
:> /tmp/mfz-web-cmd

# ## ## ··· ######################################### ## #
url=$(sqlite3 -separator $sep /tmp/h \
  "select substr(title, 1, $cols), url from urls order by last_visit_time desc" |
  awk -F $sep '{printf "%-'$cols's  %s\n", $1, $2}'| fzf --reverse --prompt='sel one ' | sed 's#.*\(https*://\)#\1#')

[ -z "$url" ] || echo "chromium --app=$url" 2>&1 | tee /tmp/mfz-web-cmd

exit
